In [33]:
import tensorflow

In [34]:
import keras


In [35]:
import numpy as np

In [36]:
x = np.array([1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0],dtype=float)
y = np.array([3.0,6.0,9.0,12.0,15.0,18.0,21.0,24.0,27.0,30.0], dtype=float)

In [37]:
model = keras.Sequential([keras.layers.Dense(units=1,input_shape=[1])])

In [40]:
model.compile(optimizer='sgd', loss='mean_squared_error')

In [43]:
model.fit(x, y,epochs=100)


Epoch 1/100
1/1 [==============================] - 0s 6ms/step - loss: 0.0246
Epoch 2/100
1/1 [==============================] - 0s 8ms/step - loss: 0.0244
Epoch 3/100
1/1 [==============================] - 0s 5ms/step - loss: 0.0242
Epoch 4/100
1/1 [==============================] - 0s 8ms/step - loss: 0.0240
Epoch 5/100
1/1 [==============================] - 0s 6ms/step - loss: 0.0238
Epoch 6/100
1/1 [==============================] - 0s 5ms/step - loss: 0.0236
Epoch 7/100
1/1 [==============================] - 0s 9ms/step - loss: 0.0234
Epoch 8/100
1/1 [==============================] - 0s 6ms/step - loss: 0.0232
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 0.0230
Epoch 10/100
1/1 [==============================] - 0s 7ms/step - loss: 0.0228
Epoch 11/100
1/1 [==============================] - 0s 6ms/step - loss: 0.0226
Epoch 12/100
1/1 [==============================] - 0s 11ms/step - loss: 0.0224
Epoch 13/100
1/1 [==============================] - 0s 6ms/s

In [45]:
model.predict([2])

array([[6.1584115]], dtype=float32)

In [46]:
from keras.datasets import mnist

In [47]:

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [50]:
train_labels[0]

5

In [51]:
from keras import models
from keras import layers

In [52]:
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [53]:
network.compile(optimizer='rmsprop',
 loss='categorical_crossentropy',
 metrics=['accuracy'])

In [55]:
train_images = train_images.reshape((60000, 28 * 28))

In [56]:
train_images[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [57]:
train_images = train_images.astype('float32') / 255

In [58]:
train_images[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [59]:
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [61]:
train_labels[0]

5

In [64]:
from keras.utils import np_utils

In [66]:
train_labels = np_utils.to_categorical(train_labels)

In [67]:
train_labels[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [68]:
test_labels = np_utils.to_categorical(test_labels)

In [70]:
network.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 14s 7ms/step - loss: 0.0317 - accuracy: 0.9921
Epoch 2/5
1875/1875 [==============================] - 13s 7ms/step - loss: 0.0252 - accuracy: 0.9932
Epoch 3/5
1875/1875 [==============================] - 13s 7ms/step - loss: 0.0201 - accuracy: 0.9946
Epoch 4/5
1875/1875 [==============================] - 13s 7ms/step - loss: 0.0174 - accuracy: 0.9955
Epoch 5/5
1875/1875 [==============================] - 14s 7ms/step - loss: 0.0136 - accuracy: 0.9962


In [71]:
network.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 3ms/step - loss: 0.0963 - accuracy: 0.9823


[0.0963292196393013, 0.9822999835014343]