In [12]:
import numpy as np

In [10]:
# Universal Functions: Fast Element-Wise Array Functions
# Transposing Arrays and Swapping Axes
# Fancy Indexing
# Boolean Indexing
# Unique and Other Set Logic
# Sorting

# **Boolean Indexing**

In [13]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [14]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [15]:
data

array([[ 0.18530912,  0.51932452, -0.78800891, -0.70804994],
       [ 0.53241189,  0.00519908,  0.91009836, -1.12165961],
       [-0.03602939,  0.59478615,  1.65442833, -0.96132919],
       [ 1.02354063,  1.48686957, -1.14871831, -2.48560674],
       [-0.96008034,  0.91715617,  0.94666127, -0.13088728],
       [ 1.62476593, -1.29865352,  0.46728834, -0.12777479],
       [-1.9866043 , -0.14756807,  0.47439361,  2.30513587]])

In [25]:
data[names == 'Bob']

array([[ 0.18530912,  0.51932452, -0.78800891, -0.70804994],
       [ 1.02354063,  1.48686957, -1.14871831, -2.48560674]])

In [64]:
data[names == 'Bob', 0]

array([0.18530912, 1.02354063])

In [31]:
data[(names == 'Bob') | (names == 'Joe')]

array([[ 0.18530912,  0.51932452, -0.78800891, -0.70804994],
       [ 0.53241189,  0.00519908,  0.91009836, -1.12165961],
       [ 1.02354063,  1.48686957, -1.14871831, -2.48560674],
       [ 1.62476593, -1.29865352,  0.46728834, -0.12777479],
       [-1.9866043 , -0.14756807,  0.47439361,  2.30513587]])

In [32]:
data[data > 0]

array([0.18530912, 0.51932452, 0.53241189, 0.00519908, 0.91009836,
       0.59478615, 1.65442833, 1.02354063, 1.48686957, 0.91715617,
       0.94666127, 1.62476593, 0.46728834, 0.47439361, 2.30513587])

In [33]:
data[data < 0]

array([-0.78800891, -0.70804994, -1.12165961, -0.03602939, -0.96132919,
       -1.14871831, -2.48560674, -0.96008034, -0.13088728, -1.29865352,
       -0.12777479, -1.9866043 , -0.14756807])

# **Fancy Indexing**

In [36]:
arr = np.arange(32).reshape((8, 4))

In [35]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [37]:
arr[2,3]

11

In [38]:
arr[arr == 11]

array([11])

In [55]:
temp_arr = arr[[1,3,5,7]]

In [65]:
temp_arr

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

In [69]:
np.array([temp_arr[:,0] , temp_arr[:,3]])

array([[ 4, 12, 20, 28],
       [ 7, 15, 23, 31]])

# **Transposing Arrays and Swapping Axes**

In [70]:
arr = np.arange(15).reshape((3, 5))


In [71]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [72]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [81]:
arr = np.arange(16).reshape((2, 2, 4))

In [75]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [88]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [87]:
arr.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

# **Universal Functions: Fast Element-Wise Array Functions**

In [89]:
arr = np.arange(10)

In [90]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [92]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

# **Sorting**

In [93]:
arr = np.random.randn(6)


In [94]:
arr

array([ 0.32933099, -0.51219201,  0.20054649, -0.06428938,  0.65182475,
       -0.49958275])

In [98]:
arr.sort()

In [96]:
arr

array([-0.51219201, -0.49958275, -0.06428938,  0.20054649,  0.32933099,
        0.65182475])

# **Unique and Other Set Logic**

In [102]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe','Anael'])

In [104]:
np.unique(names)

array(['Anael', 'Bob', 'Joe', 'Will'], dtype='<U5')

In [105]:
temp_names = np.array(['Bob','Umair','Anael','Ammar'])

In [106]:
np.intersect1d(names, temp_names)

array(['Anael', 'Bob'], dtype='<U5')

In [108]:
np.union1d(names, temp_names)

array(['Ammar', 'Anael', 'Bob', 'Joe', 'Umair', 'Will'], dtype='<U5')

In [110]:
np.in1d(temp_names,names)

array([ True, False,  True, False])