In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])


In [7]:
arr

array([1, 2, 3, 4, 5])

In [2]:
arr.dtype

dtype('int64')

In [10]:
arr = arr.astype('int8')

In [11]:
arr.dtype

dtype('int8')

In [48]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])


In [23]:
# Sum Operation

In [20]:
arr = arr + arr

In [21]:
arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [24]:
# Subtract Operation

In [49]:
arr = arr - arr

In [50]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
arr = arr + 5

In [52]:
arr

array([[5., 5., 5.],
       [5., 5., 5.]])

In [53]:
arr = 1/arr

In [54]:
arr

array([[0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2]])

In [32]:
div =  5/3

In [33]:
div

1.6666666666666667

In [35]:
arr

array([[0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2]])

In [56]:
arr2d = np.arange(6).reshape(2,3)

In [57]:
arr2d

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
arr == arr2d

array([[False, False, False],
       [False, False, False]])

In [44]:
arr

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float16)

In [59]:
# Slicing

In [92]:
 arr = np.arange(10)

In [76]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr[4:6]

array([4, 5])

In [78]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr[4:7] = 12

In [80]:
arr

array([ 0,  1,  2,  3, 12, 12, 12,  7,  8,  9])

In [81]:
arr_slice = arr[4:7].copy()

In [82]:
arr_slice

array([12, 12, 12])

In [83]:
arr_slice[1] = 45

In [84]:
arr_slice

array([12, 45, 12])

In [93]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
arr[:]

array([ 0,  1,  2,  3, 12, 12, 12,  7,  8,  9])

In [94]:
new_slice = arr[4:7].copy()

In [95]:
new_slice

array([4, 5, 6])

In [96]:
arr[:] = 0

In [97]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [98]:
new_slice

array([4, 5, 6])

In [99]:
arr3d = np.arange(45).reshape(3,3,5)

In [100]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [101]:
arr2d = np.arange(20).reshape(4,5)

In [102]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [118]:
arr3d = np.array([arr2d[0,2:4],arr2d[2,2:4]])

In [119]:
arr3d

array([[ 2,  3],
       [12, 13]])