In [2]:
import pandas as pd
import numpy as np

In [3]:
arr1d = np.arange(10)

In [4]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2d = np.arange(12).reshape(3,4)

In [6]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
# Series

In [8]:
obj = pd.Series([4, 7, -5, 3])

In [19]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [20]:
obj.values

array([ 4,  7, -5,  3])

In [21]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [22]:
obj = pd.Series([1,2,3,4,5],index=['f1','f2','f3','f4','f5'])

In [23]:
obj

f1    1
f2    2
f3    3
f4    4
f5    5
dtype: int64

In [24]:
obj.index

Index(['f1', 'f2', 'f3', 'f4', 'f5'], dtype='object')

In [31]:
obj[0:4]

f1    1
f2    2
f3    3
f4    4
dtype: int64

In [29]:
obj['f1']

1

In [32]:
obj[['f1','f4']]

f1    1
f4    4
dtype: int64

In [34]:
obj[obj > 2]

f3    3
f4    4
f5    5
dtype: int64

In [35]:
'f3' in obj

True

In [36]:
obj['f3']

3

In [41]:
obj['f6'] = 6

In [42]:
obj

f1    1
f2    2
f3    3
f4    4
f5    5
f6    6
dtype: int64

In [58]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [59]:
dict_series1 = pd.Series(sdata)

In [60]:
print(dict_series1)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64


In [46]:
'Texas' in dict_series

True

In [51]:
states = ['California', 'Ohio', 'Oregon', 'Texas']


In [52]:
dict_series = pd.Series(sdata, index=states)

In [71]:
final_result = dict_series + dict_series1

In [55]:
pd.notnull(dict_series)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [74]:
final_result.index.name = 'State'

In [77]:
final_result.name = 'Population'

In [78]:
final_result

State
California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
Name: Population, dtype: float64